const { contextBridge, ipcRenderer } = require("electron");

const call = (name, input) => ipcRenderer.invoke(`router-control:${name}`, input);

const routerControl = Object.freeze({
  platform: process.platform,
  minimizeWindow: () => call("minimizeWindow"),
  toggleMaximizeWindow: () => call("toggleMaximizeWindow"),
  closeWindow: () => call("closeWindow"),
  getSnapshot: () => call("getSnapshot"),
  getChatGptSession: () => call("getChatGptSession"),
  getHealth: () => call("getHealth"),
  getRoutingStatus: () => call("getRoutingStatus"),
  setRoutingConnected: (enabled) => call("setRoutingConnected", { enabled }),
  getProviders: () => call("getProviders"),
  getConnections: () => call("getConnections"),
  getLocalGgufModels: () => call("getLocalGgufModels"),
  discoverLocalGgufModels: (root) => call("discoverLocalGgufModels", { root }),
  addLocalGgufModel: (input) => call("addLocalGgufModel", input),
  startLocalGgufModel: (id) => call("startLocalGgufModel", { id }),
  stopLocalGgufModel: (id) => call("stopLocalGgufModel", { id }),
  testLocalGgufModel: (id) => call("testLocalGgufModel", { id }),
  setLocalGgufPublished: (id, published) => call("setLocalGgufPublished", { id, published }),
  removeLocalGgufModel: (id) => call("removeLocalGgufModel", { id }),
  addConnection: (input) => call("addConnection", input),
  updateConnection: (providerId, input) => call("updateConnection", { providerId, ...input }),
  setConnectionEnabled: (providerId, enabled) => call("setConnectionEnabled", { providerId, enabled }),
  setConnectionCredential: (providerId, credential) => call("setConnectionCredential", { providerId, credential }),
  clearConnectionCredential: (providerId) => call("clearConnectionCredential", { providerId }),
  addConnectionModel: (providerId, modelId, contextWindow) =>
    call("addConnectionModel", { providerId, modelId, contextWindow }),
  removeConnectionModel: (providerId, modelId) => call("removeConnectionModel", { providerId, modelId }),
  testConnection: (providerId) => call("testConnection", { providerId }),
  testConnectionInput: (input) => call("testConnectionInput", input),
  discoverConnectionModels: (providerId) => call("discoverConnectionModels", { providerId }),
  removeConnection: (providerId) => call("removeConnection", { providerId }),
  getFallback: () => call("getFallback"),
  setFallback: (enabled, chain) => call("setFallback", { enabled, chain }),
  getProjectRoute: (project) => call("getProjectRoute", { project }),
  setProjectRoute: (project, model) => call("setProjectRoute", { project, model }),
  clearProjectRoute: (project) => call("clearProjectRoute", { project }),
  discoverProviderModels: (providerId, options) =>
    call("discoverProviderModels", { providerId, refresh: Boolean(options?.refresh) }),
  getAccountUsage: () => call("getAccountUsage"),
  getProviderUsage: () => call("getProviderUsage"),
  getLocalModels: () => call("getLocalModels"),
  getVisionBridge: () => call("getVisionBridge"),
  getToolResultAging: () => call("getToolResultAging"),
  getDoctor: () => call("getDoctor"),
  repairInstall: () => call("repairInstall"),
  getPresence: () => call("getPresence"),
  getHarnesses: () => call("getHarnesses"),
  getContextSessions: () => call("getContextSessions"),
  refreshAll: () => call("refreshAll"),
  setProviderEnabled: (providerId, enabled) => call("setProviderEnabled", { providerId, enabled }),
  addProviderModels: (providerId, modelIds) => call("addProviderModels", { providerId, modelIds }),
  connectProvider: (providerId) => call("connectProvider", { providerId }),
  saveProviderCredential: (providerId, credential) => call("saveProviderCredential", { providerId, credential }),
  removeProviderCredential: (providerId) => call("removeProviderCredential", { providerId }),
  setSubagentMode: (mode) => call("setSubagentMode", { mode }),
  setSubagentModel: (slug, enabled) => call("setSubagentModel", { slug, enabled }),
  setSubagentEffort: (slug, effort) => call("setSubagentEffort", { slug, effort }),
  certifySubagentModels: (slugs) => call("certifySubagentModels", { slugs }),
  setSubagentSelection: (selectAll) => call("setSubagentSelection", { selectAll }),
  setPickerModel: (slug, visible) => call("setPickerModel", { slug, visible }),
  setPickerModels: (showAll) => call("setPickerModels", { showAll }),
  installLocalModel: (tag, force = false) => call("installLocalModel", { tag, force, yes: true }),
  installLocalMlx: () => call("installLocalMlx", { yes: true }),
  cancelLocalMlx: () => call("cancelLocalMlx"),
  uninstallLocalModel: (tag) => call("uninstallLocalModel", { tag }),
  setLocalModelEnabled: (tag, enabled) => call("setLocalModelEnabled", { tag, enabled }),
  benchmarkLocalModel: (tag) => call("benchmarkLocalModel", { tag }),
  controlLocalRuntime: (action) => call("controlLocalRuntime", { action }),
  setVisionBridgeEnabled: (enabled) => call("setVisionBridgeEnabled", { enabled }),
  setVisionBridgeEngine: (engine, effort) => call("setVisionBridgeEngine", { engine, effort }),
  setVisionBridgeEffort: (effort) => call("setVisionBridgeEffort", { effort }),
  downloadVisionModel: (tag) => call("downloadVisionModel", { tag }),
  useLocalVisionModel: (tag) => call("useLocalVisionModel", { tag }),
  benchmarkVisionModel: (tag) => call("benchmarkVisionModel", { tag }),
  setToolResultAging: (enabled) => call("setToolResultAging", { enabled }),
  setNativeToolResultAging: (enabled) => call("setNativeToolResultAging", { enabled }),
  setToolResultRetentionTtl: (days) => call("setToolResultRetentionTtl", { days }),
  setDefaultModel: (slug) => call("setDefaultModel", { slug }),
  setRouterDefault: (slug) => call("setRouterDefault", { slug }),
  clearRouterDefault: () => call("clearRouterDefault"),
  setSignedRouting: (enabled) => call("setSignedRouting", { enabled }),
  setChatGptSessionSharing: (enabled) => call("setChatGptSessionSharing", { enabled }),
  setPresence: (mode) => call("setPresence", { mode }),
  controlService: (action) => call("controlService", { action }),
  controlTray: (action) => call("controlTray", { action }),
  launchHarness: (harnessId, surface) => call("launchHarness", { harnessId, surface }),
  installHarness: (harnessId) => call("installHarness", { harnessId }),
  openHarnessSession: (harnessId, sessionId, surface, model) => call("openHarnessSession", { harnessId, sessionId, surface, model }),
  openExternal: (url) => call("openExternal", { url }),
  onOperation(listener) {
    if (typeof listener !== "function") throw new TypeError("Operation listener must be a function.");
    const wrapped = (_event, payload) => listener(payload);
    ipcRenderer.on("router-control:operation", wrapped);
    return () => ipcRenderer.removeListener("router-control:operation", wrapped);
  },
});

contextBridge.exposeInMainWorld("routerControl", routerControl);
